Add sample of templates
furukawa-laboratory/rookies_workout_2021 pull request #6
Opened 2021-04-12 00:26 UTC by tanacchi

Issues と PullRequests のテンプレートを作成します。
たたき台として去年と同じものを追加しました。
どこかで時間とって話し合いたいです。

2021-04-26 01:34 UTC, kz-halfmoon requested changes
獲得するスキル欄も，アクションリストと同様にチェックボックス形式の方がいいかもです．
このトレーニングを通じて，自分がどう変化するかを意識してコレらのリストを考えるという性質上，チェックマークがつけられるような形式に整えておいた方がベターだと思います．
全体としては，記述者の裁量権が大きくて自由に書けるようになってていいと思います！

2021-04-27 01:51 UTC, tanacchi commented
>獲得するスキル欄]

これは issue の話？Pullrequest の話？
（場所指定でコメントもらえるとありがたいっす・・・）

2021-04-27 08:40 UTC, kz-halfmoon commented
両方ですね．
獲得（する／できた）スキルとしてチェックがつけられるように具体化して目標を掲げるのが大事と思うんで，issueに「獲得するスキル」欄として目標を掲げておき，プルリク書く時にコピペしてからチェックマークつけながら振り返る運用イメージです．

2021-04-27 11:29 UTC, tanacchi commented
なるほど！
ありがとうございます．

2021-04-27 13:10 UTC, tanacchi commented
更新しました！

2021-04-28 00:14 UTC, kz-halfmoon approved these changes

2021-04-28 00:19 UTC, kz-halfmoon commented
更新ありがとうございます！
修正もOKなので廣田はapproveです

2021-04-28 00:36 UTC, merged